# Generated by Django 4.2.9 on 2024-07-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emenitites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_image', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('emenities', models.ManyToManyField(to='book.emenitites')),
            ],
        ),
    ]
